In [1]:
'''
@Author: Santanu Mohapatra
@Date: 16/06/2021
@Last Modified by: Santanu Mohapatra
@Last Modified Time: 12:20 PM
@Title: Python program to print 3X3 matrix.
'''

import numpy as np 

mymatrix = np.arange(2, 11).reshape(3, 3)
print(mymatrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
