In [5]:
'''
@Author: Santanu Mohapatra
@Date: 16/06/2021
@Last Modified by: Santanu Mohapatra
@Last Modified Time: 14:30 PM
@Title: Python program to convert a list of and tuple into arrays.
'''

import numpy as np 

mylist = np.array([1,2,3,4,5,6,7,8])
print(mylist)
mytuple = ([8,4,6], [1,2,3])
print(np.asarray(mytuple))

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]
