In [4]:
'''
@Author: Santanu Mohapatra
@Date: 17/06/2021
@Last Modified by: Santanu Mohapatra
@Last Modified Time: 12:25 PM
@Title: Python program to create a 3-D array with ones on a diagonal and zero elsewhere.
'''

import numpy as np 

mymatrix = np.eye(3)
print(mymatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
