In [2]:
'''
@Author: Santanu Mohapatra
@Date: 17/06/2021
@Last Modified by: Santanu Mohapatra
@Last Modified Time: 13:25 PM
@Title: Python program to multiply the matrix elements by 3.
'''

import numpy as np 

mymatrix = np.array([0,1,2,3,4,5,6,7,8,9,10,11]).reshape(3,4)
multiply = mymatrix*3
print(multiply)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
