In [10]:
'''
@Author: Santanu Mohapatra
@Date: 16/06/2021
@Last Modified by: Santanu Mohapatra
@Last Modified Time: 13:20 PM
@Title: Python program to print different patterns of the array.
'''

import numpy as np 

'''
Description: Declare 2D Array of 1s.
'''
myarray1 = np.ones(25).reshape(5, 5)
print(myarray1)

'''
Description: Create a 2d array with 1 on the border and 0 inside.
'''
myarray1[1:-1, 1:-1] = 0
print(myarray1)

'''
Description: Declare 2D Array of 0s.
'''
myarray2 = np.zeros(25).reshape(5, 5)
print(myarray2)

'''
Description: Create a 2d array with 0 on the border and 1 inside.
'''
myarray2[1:-1, 1:-1] = 1
print(myarray2)

'''
Description: Declare 2D Array of 0s.
'''
myarray3 = np.zeros((8,8),dtype=int)

'''
Description: Print the checkboard.
'''
myarray3[1::2,::2] = 1
myarray3[::2,1::2] = 1
print(myarray3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
